package com.naztech.oms.service;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;

/**
 * DSE bond pricing — clean price ⇄ yield-to-maturity, accrued interest, dirty price — implementing
 * the formula in the DSE <em>Bond Trading with Yield</em> BRS (V2, 23-05-2026), §1.1.2.
 *
 * <p>The previous version of this class was a textbook present-value loop that discounted over whole
 * coupon periods. That is the formula for a bond that always settles exactly on a coupon date, and no
 * bond ever does. The consequences were measured against DSE's own worked examples before the rewrite:
 * a bond inside its final coupon period priced to exactly par (DSE example B.1 expects 100.1336), and
 * a 13-year bond's yield came out ~2 basis points wrong (B.3 expects 8.0906%). Two basis points on a
 * government bond is not rounding, it is money.
 *
 * <h2>The DSE formula, as implemented here</h2>
 * Coupon dates are generated by stepping back from maturity by the coupon period. With
 * {@code d} = days from settlement to the next coupon, {@code T} = days in the current coupon period
 * (both in <b>actual days — Actual/Actual</b>, the convention the BRS requires and the one that
 * reproduces its examples), {@code N} = coupons remaining, {@code c} = annual coupon rate,
 * {@code f} = coupon frequency and {@code v = 1/(1 + y/f)}:
 *
 * <pre>
 *   N &gt; 1:  Dirty = Σ_{k=1..N} (F·c/f)·v^(k-1+d/T)  +  F·v^(N-1+d/T)
 *   N = 1:  Dirty = F·(1 + c/f) / (1 + (d/T)·(y/f))        ← simple interest; the BRS gives this
 *                                                             case its own formula and so do we
 *   Accrued = F·(c/f)·(T-d)/T
 *   Clean   = Dirty − Accrued
 * </pre>
 *
 * <p>Yield-from-price inverts this by bisection over <b>[-50%, +200%]</b> — the lower bound is
 * negative because BRS §1.1.3 explicitly requires negative yields to be calculated and accepted (a
 * bond above par close to maturity genuinely has one), and the old floor of +0.0001% silently made
 * that impossible.
 *
 * <p>Everything takes a <b>settlement date</b>, not a trade date: accrued interest belongs to whoever
 * holds the bond at settlement, which is also what makes the ex-coupon case (BRS example A.2) fall out
 * naturally — a settlement that lands after the coupon date accrues from that coupon date, i.e. one
 * day, not a hundred and eighty.
 *
 * <p>Verified against the BRS worked examples in {@code BondMathTest}: B.1 (clean 100.1336, accrued
 * 4.8267, dirty 104.9603) and B.3 (yield 8.0906%). Those numbers are the acceptance test — DSE wrote
 * them down, so "correct" is not a matter of opinion.
 *
 * <p>Perpetuals (maturity == null) keep the {@code price = coupon/yield} consol formula for the
 * ticket's convenience, though per BRS §1.1.5 perpetuals (PRPTL) list on ALTDBT and trade like equity.
 */
public final class BondMath {

    private BondMath() {}

    /** Yield bisection bounds, in percent. The negative side is a BRS requirement (§1.1.3), not a flourish. */
    private static final double YIELD_LO = -50.0;
    private static final double YIELD_HI = 200.0;

    /** Clean price per bond unit implied by an annual yield-to-maturity (%). Settlement-date based. */
    public static BigDecimal priceFromYield(double face, double couponPct, int freq, LocalDate maturity,
                                            LocalDate settle, double yieldPct) {
        int f = clampFreq(freq);
        double c = couponPct / 100.0;
        if (maturity == null) {                                  // perpetual consol: price = coupon / yield
            double i = (yieldPct / 100.0) / f;
            return i <= 0 ? bd(face) : bd(face * (c / f) / i);
        }
        if (!maturity.isAfter(settle)) {
            return bd(face);                                     // matured: nothing left to discount
        }
        Period p = period(maturity, f, settle);
        double dOverT = p.d / (double) p.t;
        double couponAmt = face * c / f;
        double dirty;
        if (p.n == 1) {
            // Inside the final coupon period the BRS prescribes simple interest, not compounding —
            // the general formula overstates the discount over a fraction of one period.
            dirty = face * (1 + c / f) / (1 + dOverT * (yieldPct / 100.0) / f);
        } else {
            double v = 1.0 / (1 + (yieldPct / 100.0) / f);
            double pv = 0;
            for (int k = 1; k <= p.n; k++) {
                pv += couponAmt * Math.pow(v, k - 1 + dOverT);
            }
            pv += face * Math.pow(v, p.n - 1 + dOverT);
            dirty = pv;
        }
        double accrued = face * (c / f) * ((p.t - p.d) / (double) p.t);
        return bd(dirty - accrued);
    }

    /**
     * Annual yield-to-maturity (%) implied by a clean price — monotone bisection, and the range
     * includes negative yields because the BRS says it must.
     */
    public static BigDecimal yieldFromPrice(double face, double couponPct, int freq, LocalDate maturity,
                                            LocalDate settle, double cleanPrice) {
        double lo = YIELD_LO, hi = YIELD_HI;
        for (int it = 0; it < 200; it++) {
            double mid = (lo + hi) / 2;
            double p = priceFromYield(face, couponPct, freq, maturity, settle, mid).doubleValue();
            if (p > cleanPrice) lo = mid; else hi = mid;         // price falls as yield rises
        }
        return bd((lo + hi) / 2);
    }

    /**
     * Accrued interest per bond unit at the settlement date — Actual/Actual over the real coupon
     * schedule: {@code F·(c/f)·daysSinceCoupon/daysInPeriod}. Zero for perpetuals (no schedule to
     * accrue against) and matured bonds.
     */
    public static BigDecimal accrued(double face, double couponPct, int freq, LocalDate maturity, LocalDate settle) {
        if (maturity == null || !maturity.isAfter(settle)) return BigDecimal.ZERO;
        int f = clampFreq(freq);
        Period p = period(maturity, f, settle);
        return bd(face * (couponPct / 100.0 / f) * ((p.t - p.d) / (double) p.t));
    }

    public static BigDecimal dirty(BigDecimal clean, BigDecimal accrued) {
        return clean.add(accrued).setScale(4, RoundingMode.HALF_UP);
    }

    // ------------------------------------------------------------------ coupon schedule

    /** d = actual days settle→next coupon; t = actual days in the period; n = coupons still to pay. */
    private record Period(long d, long t, int n) {}

    /**
     * Locate the settlement date inside the bond's coupon schedule.
     *
     * <p>The schedule is generated by stepping <em>back</em> from maturity by the coupon period —
     * which is how the venue does it and why the day counts land on DSE's exact numbers (example B.1's
     * 36/181/145 are actual days against a schedule anchored at the 8th of the month, from maturity).
     */
    private static Period period(LocalDate maturity, int freq, LocalDate settle) {
        int stepMonths = 12 / freq;
        List<LocalDate> after = new ArrayList<>();               // coupons still to be paid, oldest last
        LocalDate cd = maturity;
        while (cd.isAfter(settle)) {
            after.add(cd);
            cd = cd.minusMonths(stepMonths);
        }
        LocalDate prev = cd;                                     // last coupon on/before settlement
        LocalDate next = after.get(after.size() - 1);            // first coupon after settlement
        long d = ChronoUnit.DAYS.between(settle, next);
        long t = Math.max(1, ChronoUnit.DAYS.between(prev, next));
        return new Period(d, t, after.size());
    }

    private static int clampFreq(int freq) {
        return Math.max(1, Math.min(12, freq));                  // must divide 12 for month stepping
    }

    private static BigDecimal bd(double v) { return BigDecimal.valueOf(v).setScale(4, RoundingMode.HALF_UP); }
}
